### PR TITLE
Fixed a few missing i18n keys

### LINKED ISSUE #1395: Admin view - Auction show - Auction accepted - Messaging broken
I recently accepted an auction by clicking the "Accept" button and the messaging seems broken

To duplicate:
Go to https://micropurchase.18f.gov/admin/auctions/44

Expected behavior:
You see the appropriate message https://github.com/18F/micropurchase/issues/1016

Actual behavior:
You see an error

screen shot 2016-10-27 at 11 45 49 am

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #1395 

I added an initializer for i18n that will cause missing keys to throw exceptions in development or test rather than display the `missing translation: ...` string. This revealed a few other cases of missing keys I have fixed as well.

### CODE REVIEW

File: config/initializers/i18n_test.rb [hunk 1]
```diff
@@ -0,0 +1,13 @@
+if Rails.env.test? || Rails.env.development?
+  class I18n::JustRaiseExceptionHandler < I18n::ExceptionHandler
```
Comment (adelevie) [inline config/initializers/i18n_test.rb]: nice class name

**Comment by adelevie** [comment]
LGTM, merging when :green_apple:
